"""Patch generator for config findings (v0.5).

Motivated by SecOps audit retrospective:
  > What would have made the recommendations better:
  > A patch for F-1 (~30 lines). I offered one at the end of v2 but never
  > wrote it. A diff is worth more than ten paragraphs of prose.

For config findings that have unambiguous fixes, we generate a ready-to-
apply patch next to the report. The user can inspect and apply manually
— we never auto-apply (that would be active defense, outside scope).

Currently generates patches for:
  - config.claude-code.permissive.no-secret-deny — adds deny rules
  - config.claude-code.permissive.wildcard-allow — warning, doesn't auto-fix
    (user's actual allowlist needs manual design)
  - config.claude-code.permissive.dangerous-mode — removes the flag
  - config.codex.permissive.full-auto — sets approval_mode = "on-request"

Output format: a directory `patches/` next to the report containing:
  - patches/patch-summary.md — human-readable index
  - patches/<finding-id>/apply.sh — bash script to apply (idempotent)
  - patches/<finding-id>/before.json or .toml — snapshot of current state
  - patches/<finding-id>/after.json or .toml — proposed state
  - patches/<finding-id>/diff.patch — unified diff
"""
from __future__ import annotations

import difflib
import json
import shlex
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


# Default deny rules for the no-secret-deny finding.
# Based on common secret file locations.
DEFAULT_DENY_RULES = [
    "Read(~/.env)",
    "Read(~/.env.*)",
    "Read(~/.ssh/**)",
    "Read(~/.aws/credentials)",
    "Read(~/.aws/config)",
    "Read(~/.gnupg/**)",
    "Read(~/.docker/config.json)",
    "Read(~/.kube/config)",
    "Read(**/*.pem)",
    "Read(**/*.key)",
    "Read(**/id_rsa*)",
    "Read(**/id_ed25519*)",
]


def generate_patch_for_finding(
    finding: dict,
    patches_dir: Path,
) -> Optional[Dict[str, str]]:
    """Generate a patch for a single finding if we know how to fix it.

    Returns a dict with patch metadata, or None if we can't fix this finding
    automatically. `finding` is the dict form from the JSON report.
    """
    rule_id = finding.get("rule_id", "")

    if rule_id == "config.claude-code.permissive.no-secret-deny":
        return _patch_claude_secret_deny(finding, patches_dir)
    if rule_id == "config.claude-code.permissive.dangerous-mode":
        return _patch_claude_dangerous_mode(finding, patches_dir)
    if rule_id == "config.codex.permissive.full-auto":
        return _patch_codex_full_auto(finding, patches_dir)

    return None  # Don't know how to patch this one


def _write_patch_artifacts(
    patches_dir: Path,
    finding_id: str,
    target_path: Path,
    before_text: str,
    after_text: str,
    description: str,
) -> Dict[str, str]:
    """Write before/after/diff artifacts and an apply.sh script.
    Returns metadata dict."""
    finding_dir = patches_dir / finding_id.replace("/", "_").replace(".", "_")
    finding_dir.mkdir(parents=True, exist_ok=True)

    suffix = target_path.suffix or ".txt"
    before_path = finding_dir / f"before{suffix}"
    after_path = finding_dir / f"after{suffix}"
    diff_path = finding_dir / "diff.patch"
    apply_path = finding_dir / "apply.sh"

    before_path.write_text(before_text, encoding="utf-8")
    after_path.write_text(after_text, encoding="utf-8")

    # Unified diff
    diff = difflib.unified_diff(
        before_text.splitlines(keepends=True),
        after_text.splitlines(keepends=True),
        fromfile=str(target_path) + " (current)",
        tofile=str(target_path) + " (proposed)",
    )
    diff_path.write_text("".join(diff), encoding="utf-8")

    # apply.sh — idempotent, with backup
    quoted_target = shlex.quote(str(target_path))
    apply_script = f"""#!/usr/bin/env bash
# Patch for: {finding_id}
# Target: {target_path}
# Auto-generated by agent-audit. Review before running.

set -e

TARGET={quoted_target}
AFTER="$(dirname "$0")/after{suffix}"

if [ ! -f "$TARGET" ]; then
    echo "ERROR: target file $TARGET not found"
    exit 1
fi

# Backup current
BACKUP="${{TARGET}}.backup.$(date +%s)"
cp -- "$TARGET" "$BACKUP"
echo "Backup: $BACKUP"

# Apply
cp -- "$AFTER" "$TARGET"
echo "Applied: $TARGET"
echo ""
echo "If something went wrong, restore with:"
echo "  cp -- $BACKUP $TARGET"
"""
    apply_path.write_text(apply_script, encoding="utf-8")
    apply_path.chmod(0o755)

    return {
        "finding_id": finding_id,
        "target": str(target_path),
        "description": description,
        "patch_dir": str(finding_dir),
        "apply_script": str(apply_path),
        "diff": str(diff_path),
    }


def _patch_claude_secret_deny(
    finding: dict,
    patches_dir: Path,
) -> Optional[Dict[str, str]]:
    """Add deny rules for secret paths to Claude Code settings.json."""
    # Extract target path from evidence
    evidence = finding.get("evidence", [])
    if not evidence:
        return None
    source = evidence[0].get("source")
    if not source:
        return None
    target = Path(source)
    if not target.exists():
        # Can't patch what we can't read
        return None

    try:
        current = json.loads(target.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None

    before_text = json.dumps(current, indent=2)

    # Add missing deny rules
    permissions = current.setdefault("permissions", {})
    existing_deny = permissions.get("deny") or []
    existing_lower = {str(r).lower() for r in existing_deny}

    # Only add rules not already present
    for rule in DEFAULT_DENY_RULES:
        if rule.lower() not in existing_lower:
            existing_deny.append(rule)
    permissions["deny"] = existing_deny

    after_text = json.dumps(current, indent=2)

    if before_text == after_text:
        return None  # Nothing changed (all rules already present)

    return _write_patch_artifacts(
        patches_dir,
        finding["rule_id"],
        target,
        before_text,
        after_text,
        "Add deny rules for secret paths (~/.env, ~/.ssh, etc.)",
    )


def _patch_claude_dangerous_mode(
    finding: dict,
    patches_dir: Path,
) -> Optional[Dict[str, str]]:
    """Remove skipDangerousModePermissionPrompt from settings.json."""
    evidence = finding.get("evidence", [])
    if not evidence:
        return None
    source = evidence[0].get("source")
    if not source:
        return None
    target = Path(source)
    if not target.exists():
        return None

    try:
        current = json.loads(target.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None

    before_text = json.dumps(current, indent=2)

    if "skipDangerousModePermissionPrompt" not in current:
        return None
    current.pop("skipDangerousModePermissionPrompt", None)

    after_text = json.dumps(current, indent=2)

    return _write_patch_artifacts(
        patches_dir,
        finding["rule_id"],
        target,
        before_text,
        after_text,
        "Remove skipDangerousModePermissionPrompt flag",
    )


def _patch_codex_full_auto(
    finding: dict,
    patches_dir: Path,
) -> Optional[Dict[str, str]]:
    """Change approval_mode from full_auto to on-request in Codex config.toml."""
    evidence = finding.get("evidence", [])
    if not evidence:
        return None
    source = evidence[0].get("source")
    if not source:
        return None
    target = Path(source)
    if not target.exists():
        return None

    try:
        before_text = target.read_text(encoding="utf-8")
    except OSError:
        return None

    if "full_auto" not in before_text:
        return None

    # Simple line-based replacement to preserve comments/formatting
    after_lines = []
    for line in before_text.splitlines(keepends=True):
        if line.strip().startswith("approval_mode") and "full_auto" in line:
            after_lines.append('approval_mode = "on-request"\n')
        elif line.strip().startswith("sandbox") and '"none"' in line:
            after_lines.append('sandbox = "read-only"\n')
        else:
            after_lines.append(line)
    after_text = "".join(after_lines)

    if before_text == after_text:
        return None

    return _write_patch_artifacts(
        patches_dir,
        finding["rule_id"],
        target,
        before_text,
        after_text,
        "Change approval_mode to on-request, enable read-only sandbox",
    )


def generate_all_patches(
    findings: List[dict],
    patches_dir: Path,
) -> Tuple[int, Path]:
    """Generate patches for all applicable findings. Returns (count, index_path).

    If no patches generated, returns (0, patches_dir) and writes nothing.
    """
    patches_dir.mkdir(parents=True, exist_ok=True)

    generated = []
    for f in findings:
        patch = generate_patch_for_finding(f, patches_dir)
        if patch:
            generated.append(patch)

    if not generated:
        return 0, patches_dir

    # Write human-readable index
    index_lines = [
        "# agent-audit patches",
        "",
        "These patches are automatically generated fixes for config findings.",
        "They are **not** applied automatically — you must review and run apply.sh yourself.",
        "",
        "## Generated patches",
        "",
    ]
    for p in generated:
        index_lines.extend([
            f"### {p['finding_id']}",
            "",
            f"**Target:** `{p['target']}`",
            "",
            f"**Description:** {p['description']}",
            "",
            f"- Diff: `{Path(p['diff']).relative_to(patches_dir)}`",
            f"- Apply script: `{Path(p['apply_script']).relative_to(patches_dir)}`",
            "",
            "Review the diff, then apply:",
            "",
            "```bash",
            f"bash {Path(p['apply_script']).relative_to(patches_dir)}",
            "```",
            "",
            "---",
            "",
        ])

    index_path = patches_dir / "patch-summary.md"
    index_path.write_text("\n".join(index_lines), encoding="utf-8")
    return len(generated), index_path
